### ISSUE TITLE
`cast_attachments` with non-file parameters

### ISSUE THREAD

**Issue by knewter** [stavro/arc_ecto#1]
I naively tried to just replace calls to cast with calls to cast_attachments, and this causes errors with any non-attachment parameters on my models.  In essence, if you add a `name` field to the User model there will be errors reported on that field.  Also, even getting to the `new` form was problematic if there were non-attachment parameters.  I only got to the errors by hacking around a bit to get to the form first (otherwise the changeset created on `new` will throw an error re: `:empty` being an invalid dict.

Anyway, really like arc and I'm presently doing an ElixirSip on it :)  Thanks!

**Comment by eric-roland** [comment]
I saw the same behavior.  cast "works" until you try to getting the scope.

**Comment by blisscs** [comment]
Hi @knewter  and @eric-roland 

I am getting that error too.
Has anybody figured a workaround to this issue to make it works.

**Comment by stavro** [comment]
Sorry guys!

I just saw these comments - No idea why they didn't come to my email.  I am looking into this now.

**Comment by stavro** [comment]
Can you post an example that you are having problems with?

I currently do not try to combine calls to `cast` and `cast_attachments`.  This is how I currently use it:

```elixir
  def update(user, params) do
    user
    |> cast(params, ~w(), ~w(first_name last_name email))
    |> cast_attachments(params, ~w(), ~w(avatar))
  end
```

**Comment by stavro** [comment]
@knewter Thanks for the Elixir Sips writeup! I'm going to have to check it out :)

**Comment by blisscs** [comment]
Hi @stavro,
I think the above update/2 function is a changeset/2 for the model's changeset function. If not please correct me.

def changeset(user,params) do
  user
     |> cast(params, ~w(), ~w(first_name last_name email))
     |> cast_attachments(params, ~w(), ~w(avatar))
end

I tried using that for the defination of changeset/2 defination model I still get the error "unsupported dict: :empty" when creating a changeset in the function new of the controller

def new(conn, _params) do
    changeset =  Upload.changeset(%Upload{})
    render  conn, "new.html", changeset: changeset
end

My Upload model look like this -

defmodule BlogCswebInTh.Upload do
  use BlogCswebInTh.Web, :model
  use Arc.Ecto.Model

  schema "uploads" do
    field :title, :string
    field :file, BlogCswebInTh.UploadFile.Type
    timestamps
  end

  @required_fields ~w(title file) 
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
      |> cast(params, @required_fields, @optional_fields)
      |> cast_attachments(params, @required_fields, @optional_fields)
      |> validate_length(:title, min: 1)
  end
end

And my uploader look like this -

defmodule BlogCswebInTh.UploadFile do
  use Arc.Definition
  use Arc.Ecto.Definition

  # Include ecto support (requires package arc_ecto installed):
  # use Arc.Ecto.Definition

  @versions [:original]

  # To add a thumbnail version:
  # @versions [:original, :thumb]

  # Whitelist file extensions:
  # def validate({file, _}) do
  #   ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  # end
  
  # Define a thumbnail transformation:
  # def transform(:thumb, _) do
  #   {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png"}
  # end

  # Override the persisted filenames:
  # def filename(version, _) do
  #   version
  # end

  # Override the storage directory:
  # def storage_dir(version, {file, scope}) do
  #   "uploads/user/avatars/#{scope.id}"
  # end

  # Provide a default URL if there hasn't been a file uploaded
  # def default_url(version) do
  #   "/images/avatars/default_#{version}.png"
  # end
end

**Comment by stavro** [comment]
@blisscs Two things:

1.  Separate out the fields you send to `cast` and `cast_attachments`.  Use `cast` for all attributes other than `file`, and use `cast_attachments` for your file parameters. Right now you are specifying the same `@required_fields` for both.
2. The library was not properly supporting a value of `:empty` as the params.  Please upgrade your `arc_ecto` dependency to v0.1.2, try again, and let me know!

**Comment by blisscs** [comment]
I have seperated out the fields for the cast and cast_attachements the above changeset/2 function above and updated arc_ecto to v0.1.2
Please see code below.
```
def changeset(model, params \\ :empty) do
    model
      |> cast(params, ~w(title), ~w())
      |> cast_attachments(params, ~w(file),~w() )
      |> validate_length(:title, min: 1)
  end
```

After doing so I got the error
```
undefined function: Ecto.Changeset.__changeset__/0
```

<img width="1399" alt="screen shot 2015-09-01 at 09 55 37" src="https://cloud.githubusercontent.com/assets/736223/9595173/ac33541e-508f-11e5-972d-f7558a48f6f9.png">

Thank you @stavro

**Comment by stavro** [comment]
@blisscs Thank you for the feedback.  I believe this is an issue in Ecto (Reported at: https://github.com/elixir-lang/ecto/issues/914)

If you want to get around the issue temporarily, replace the atom `:empty` with an empty map (`%{}`)

**Comment by stavro** [comment]
Usage of the `:empty` atom has been fixed in Ecto master.  Until the next released version, either reference git directly, or use an empty map (`%{}`) instead of the `:empty` atom.

If you notice any other issues please open a new issue.

Thanks!

**Comment by nirev** [comment]
Thanks for the detailed answer, @stavro!
I'm just starting with Elixir/Phoenix and got the __changeset__/0 error above, nice to find all the answers I needed here :)
