### ISSUE TITLE
Ecto 3.0 emits warnings when using arc_ecto

### ISSUE THREAD

**Issue by dbernheisel** [stavro/arc_ecto#102]
When using Ecto 3.0 and arc_ecto, I see a lot of warnings about arc_ecto passing strings into `cast()` as the allowed list of param keys.

![image](https://user-images.githubusercontent.com/643967/48230128-f83a8c00-e377-11e8-82c5-0c7409c55e72.png)

Here are the ecto versions in my mix.lock

```
"ecto": {:hex, :ecto, "3.0.1", "a26605ee7b243a754e6609d1c23da27bcb22823659b07bf03f9020da92a8e4f4" ....
"ecto_sql": {:hex, :ecto_sql, "3.0.0", "8d1883376bee02a0e76b5ef797e39d04333c34b9935d0b4785dbf3cbdb571e2a" ....
```

**Comment by OvermindDL1** [comment]
This warning is still occurring with `0.11.1`.

It looks like this comment in arc_ecto may not be correct, and thus it's related code is not correct:
https://github.com/stavro/arc_ecto/blob/master/lib/arc_ecto/schema.ex#L20
```elixir
      # Cast supports both atom and string keys, ensure we're matching on both.
```

**Comment by dbernheisel** [comment]
@OvermindDL1 what's your changeset logic look like? I've been using `0.11.1` and haven't seen the warnings lately.

Mine looks something like this:

```elixir
  @required_fields ~w(first_name last_name)a
  @optional_fields ~w(user_id company phone job_title linkedin_url job_description supervisor_name other)a

  @doc false
  def changeset(struct, attrs) do
    struct
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> ensure_uuid(:id)
    |> cast_attachments(attrs, [:avatar, :other_file, :job_description_file])
    |> ...
```

**Comment by OvermindDL1** [comment]
Figured out the reason, it was caused by having the file field in the `cast` instead of `cast_attachments` (perhaps an error should be thrown instead when that is done, easy to detect because `scope` is `nil`).
