### ISSUE TITLE
arc_ecto not working with ecto 3

### ISSUE THREAD

**Issue by AppyCat** [stavro/arc_ecto#104]
Hi, I'm using Elixir 1.7.3 with Phoenix 1.4.0 with Arc 0.11.0 and Ecto 3.0

Problem is arc_ecto 0.11.0 wants Ecto 2.0

Can arc_ecto work with Ecto 3 on any other branch?

**Comment by dbernheisel** [comment]
Can you try from master now? Should be fixed with #103

**Comment by AppyCat** [comment]
Hi, it did install fine from Master :) and is working well. Thank you very much for your speedy update on that :)

Have 3 little glitches that may be of interest:

1. Its creating 2 sets of each version. So I have 4 files instead of 2.
2. When I try to override the local storage directory, it can't find the file or scope. 
3. If I set a UUID on version, it keeps changes for each pic processed and isn't reflected in the db.

Is it possible to pass in client_id or set one constant UUID for each version stored in the db?

My uploader file and controller look as follows. The function is to update, so ideally we can delete the existing versions automatically via arc or I can write some logic to do so.

CONTROLLER FUNCTION
def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)
    case Auth.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.page_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

UPLOADER FILE
defmodule UserUploader.Avatar do

  use Arc.Definition
  use Arc.Ecto.Definition

  def __storage, do: Arc.Storage.Local

  @versions [:original]

  # To add a thumbnail version:
  @versions [:original, :thumb]

  # Override the bucket on a per definition basis:
  # def bucket do
  #   :custom_bucket_name
  # end

  # Whitelist file extensions:
  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  # Define a thumbnail transformation:
  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png", :png}
  end

  # Override the persisted filenames:
  def filename(version, _) do
    "#{UUID.uuid1()}"
  end

  def storage_dir(version, _) do
    "uploads/users/"
  end

  # Provide a default URL if there hasn't been a file uploaded
  # def default_url(version, scope) do
  #   "/images/avatars/default_#{version}.png"
  # end

  # Specify custom headers for s3 objects
  # Available options are [:cache_control, :content_disposition,
  #    :content_encoding, :content_length, :content_type,
  #    :expect, :expires, :storage_class, :website_redirect_location]
  #
  # def s3_object_headers(version, {file, scope}) do
  #   [content_type: MIME.from_path(file.file_name)]
  # end
end

**Comment by AppyCat** [comment]
Hi, it did install fine from Master :) and is working well. Thank you very much for your speedy update on that :)

Have 3 little glitches that may be of interest:

1. Its creating 2 sets of each version. So I have 4 files instead of 2.
2. When I try to override the local storage directory, it can't find the file or scope. 
3. If I set a UUID on version, it keeps changes for each pic processed and isn't reflected in the db.

Is it possible to pass in client_id or set one constant UUID for each version stored in the db?

My uploader file and controller look as follows. The function is to update, so ideally we can delete the existing versions automatically via arc or I can write some logic to do so.

CONTROLLER FUNCTION
def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)
    case Auth.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.page_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

UPLOADER FILE
defmodule UserUploader.Avatar do

  use Arc.Definition
  use Arc.Ecto.Definition

  def __storage, do: Arc.Storage.Local

  @versions [:original]

  @versions [:original, :thumb]

  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png", :png}
  end

  # Override the persisted filenames:
  def filename(version, _) do
    "#{UUID.uuid1()}"
  end

  def storage_dir(version, _) do
    "uploads/users/"
  end
end

**Comment by AppyCat** [comment]
Hi, it did install fine from Master :) and is working well. Thank you very much for your speedy update on that :)

Have 3 little glitches that may be of interest:

1. Its creating 2 sets of each version. So I have 4 files instead of 2.
2. When I try to override the local storage directory, it can't find the file or scope. 
3. If I set a UUID on version, it keeps changes for each pic processed and isn't reflected in the db.

Is it possible to pass in client_id or set one constant UUID for each version stored in the db?

My uploader file and controller look as follows. The function is to update, so ideally we can delete the existing versions automatically via arc or I can write some logic to do so.

CONTROLLER FUNCTION
def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)
    case Auth.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.page_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

UPLOADER FILE
defmodule UserUploader.Avatar do

  use Arc.Definition
  use Arc.Ecto.Definition

  def __storage, do: Arc.Storage.Local

  @versions [:original]

  @versions [:original, :thumb]

  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png", :png}
  end

  def filename(version, _) do
    "#{UUID.uuid1()}"
  end

  def storage_dir(version, _) do
    "uploads/users/"
  end
end

**Comment by dbernheisel** [comment]
@appycat try using the ID from the scope instead of generating a uuid. Each time the filename function is called it will generate a new uuid which I think is the root of it misbehaving. 
If your model is using a uuid ID, then you'll need to make sure it's present before casting attachments.

**Comment by AppyCat** [comment]
Thanks, I dropped the UUID for filenaming, and am trying to use scope.id for a unique directory per user. However I get this message when I try to access scope.id

scope is accessible with IO.inspect and shows values, but scope.id throws the following error.

[error] #PID<0.5795.0> running AddictTestWeb.Endpoint (connection #PID<0.5794.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /user/1
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Avatar.store/1 is undefined (module Avatar is not available)
        Avatar.store({%Plug.Upload{content_type: nil, filename: nil, path: nil}, %AddictTest.Auth.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: 1, inserted_at: ~N[2018-11-16 02:25:49], password: "$2b$12$zn/rUYLyX73iJRYi00/H4OiXcF9VZSFiM1bzexWhPqio0zO4yBy3y", photo: %{file_name: "Andrea5.jpg", updated_at: ~N[2018-11-19 08:06:27]}, updated_at: ~N[2018-11-19 08:06:27], username: "scooby"}})
        (addict_test) lib/addict_test_web/controllers/page_controller.ex:96: AddictTestWeb.PageController.update/2
        (addict_test) lib/addict_test_web/controllers/page_controller.ex:1: AddictTestWeb.PageController.action/2
        (addict_test) lib/addict_test_web/controllers/page_controller.ex:1: AddictTestWeb.PageController.phoenix_controller_pipeline/2
        (addict_test) lib/addict_test_web/endpoint.ex:1: AddictTestWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (addict_test) lib/addict_test_web/endpoint.ex:1: AddictTestWeb.Endpoint.plug_builder_call/2
        (addict_test) lib/plug/debugger.ex:122: AddictTestWeb.Endpoint."call (overridable 3)"/2
        (addict_test) lib/addict_test_web/endpoint.ex:1: AddictTestWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/laptop/Documents/www/personal/phoenix/addict_test/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/laptop/Documents/www/personal/phoenix/addict_test/deps/cowboy/src/cowboy_stream_h.erl:293: :cowboy_stream_h.execute/3
        (cowboy) /Users/laptop/Documents/www/personal/phoenix/addict_test/deps/cowboy/src/cowboy_stream_h.erl:271: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by dbernheisel** [comment]
Here's some example code that works for me. Can you compare and see where the difference may be?

```elixir
# document.ex
defmodule MyApp.Library.Document do
  @moduledoc """
  Defines how to store documents
  """

  use Arc.Definition
  use Arc.Ecto.Definition

  @acl :public_read

  @allowed_extensions ~w(.doc .docx .xls .xlsx .pdf)
  def allowed_extensions, do: @allowed_extensions

  @doc """
  Overrides Arc.Definition function.

  Validate the file before uploading.

  Accepts {version, {file, scope}}
  Return true/false
  """
  def validate({file, _}) do
    extension = Path.extname(file.file_name)
    Enum.member?(allowed_extensions(), extension)
  end

  @doc """
  Overrides Arc.Definition function.

  Set the uploaded file's filename

  Accepts {version, {file, scope}}
  Return a string of the filename without extension.
  """
  def filename(version, {file, resource}) do
    extension = Path.extname(file.file_name)

    basename =
      file.file_name
      |> Path.basename(extension)
      |> sanitize_filename()

    "#{resource.id}-#{basename}-#{version}"
  end

  @doc """
  Overrides Arc.Definition function.

  Set the uploaded file's directory

  Accepts {version, {file, scope}}
  Return a string of the relative file path from root.
  """
  def storage_dir(_version, {_file, _resource}) do
    "uploads/resources/activities"
  end

  @spec sanitize_filename(String.t()) :: String.t()
  def sanitize_filename(filename) do
    filename |> String.replace(~r/[^A-Za-z0-9]/, "_", global: true)
  end
end


# my schema
defmodule MyApp.Library.Resource do
  @moduledoc """
  Represents resources in the library.
  """

  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}

  schema "resources" do
    field(:activity_file, Library.Document.Type)

    timestamps(type: :utc_datetime)
  end

  @required_fields ~w()a
  @optional_fields ~w()a
  @attachment_fields ~w(activity_file)a

  @doc false
  def changeset(struct, attrs) do
    struct
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> ensure_uuid(:id)
    |> cast_attachments(attrs, @attachment_fields)
  end

  @doc "Ensure there's a UUID in the given field"
  @spec ensure_uuid(Ecto.Changeset.t(), atom()) :: Ecto.Changeset.t()
  def ensure_uuid(changeset, field) do
    case get_field(changeset, field) do
      nil -> changeset |> put_change(field, Ecto.UUID.generate())
      _ -> changeset
    end
  end
end

**Comment by AppyCat** [comment]
I would say upon testing it, its not working seamlessly with Phoenix 1.4 and Elixir 1.7.3. The two key areas are:

1. Having the change to file version reflect accordingly in the db
2. Being able to override the directory with the user's id as directory name.

Every time I try to set the scope and then use scope.id I get an error message. If I override it with user, it reflects the values using IO.inspect but the moment I try to use user.id to set the directory name, it throws an error.

I'll keep trying with the code you were kind enough to share. Thanks for all your help.

**Comment by AppyCat** [comment]
If I avoid filename and storage, it works fine. Transformations work seamlessly. Glitch seems to be in in overriding the filename, it does change the file name, but that is not reflected in the DB update.

The update function is what I'm testing on, rather than create.

storage unable to get a unique id to set a unique directory.

Perhaps it may be an idea to set a 3rd arg to the storage macro whereby one can send custom attributes to use? Perhaps its already possible, I'm still in the process of becoming more well versed in Elixir and the functional approach :)

I looked at the code in your plugin, very concise and small, good example to study. Checking your example again.

**Comment by AppyCat** [comment]
I just updated to arc_ect0 3.0.1 and the versions is working fine now. Reflecting the right name in the db. So that leaves just the passing of a user.id to set the dir name in the storage macro. Thanks for all your feedback.

**Comment by AppyCat** [comment]
filename and storage are not working if I override either. Filename change is reflected in the outputted file as version, but in the db its the original file name.

storage can't override as I'm unable to get scope.id

Am using Phoenix 1.4.0, Elixir 1.7.3 and arc_ecto 3.0.1

Thanks for all your help.

**Comment by AppyCat** [comment]
Here's a wish list if in sync with your project roadmap:

1. Files delete from directory if you delete the record in the db
2. Updating an image deletes previously uploaded files for the record in db
3. Ability to override either of above 2 default settings
4. Example in docs on creating a new record and getting id to pass for image creation

I tried a new test project using just arc and arc_ecto and filename and storage override not working on Phoenix 1.4.0, Elixir 1.7.3 and latest versions of arc and arc_ecto (from master branch)

If I can be of any help with the above, please let me know.

**Comment by dbernheisel** [comment]
@appycat and the changeset code? And what error are you getting?

**Comment by AppyCat** [comment]
Here's the changeset:

defmodule Arco.Members.User do
  use Ecto.Schema
  import Ecto.Changeset
  use Arc.Ecto.Schema

  schema "users" do
    field :photo, Arco.Photo.Type

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:photo])
    |> cast_attachments(attrs, [:photo])
    |> validate_required([:photo])
  end
end

Here's the error code trying to use user.id or scope.id once I set it to user in the controller:

[error] Task #PID<0.883.0> started from #PID<0.877.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (arco) lib/arco_web/uploaders/photo.ex:23: Arco.Photo.storage_dir/2
    (arc) lib/arc/storage/local.ex:3: Arc.Storage.Local.put/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<1.78569476/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Task #PID<0.882.0> started from #PID<0.877.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (arco) lib/arco_web/uploaders/photo.ex:23: Arco.Photo.storage_dir/2
    (arc) lib/arc/storage/local.ex:3: Arc.Storage.Local.put/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<1.78569476/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.877.0> of listener ArcoWeb.Endpoint.HTTP (connection #PID<0.876.0>, stream id 1) terminated
** (exit) :undef

**Comment by dbernheisel** [comment]
@appycat try not casting `photo` with cast(), leave that for `cast_attachments()`.

Also, when creating new records, they don't yet have an ID, which you're telling Arc to use to determine how it should be named or stored. You'll notice in my example I have a `ensure_uuid(:id)` which will have Ecto use that when inserting into the database. 

Alternatively you could insert the record first without an attachment, and then immediately update it to add the attachment.

**Comment by dbernheisel** [comment]
Also, I don't think this is about Ecto 3.0 anymore or a compatibility issue. If you would please close this issue, I'll also be happy to continue debugging here.

**Comment by AppyCat** [comment]
It works beautifully by simply removing :photo from cast()

Now I just need to figure out how to save it to get the ID before processing arc. Thanks for your help.

**Comment by AppyCat** [comment]
It works beautifully by simply removing :photo from cast()

Now I just need to figure out how to save it to get the ID before processing arc. Thanks for your help.

**Comment by AppyCat** [comment]
Thank you, it worked beautifully by removing :photo from cast()

I’m not sure where arc processes within the controller. Would you have an example of saving to get the new record id before updating and processing the file with arc?

**Comment by AppyCat** [comment]
I got it working by passing user_id as a hidden field in the form to get that as scope.id

But version file name changes are still not reflected in the db. File name is original in db. And in the uploads folder its the version name I defined. So when it comes to delete it hangs. That is an arc and arc_ecto issue.

I’ve used Carrierwave for years, it automatically stores the original version name in the db, and upon delete, removes related versions. The model.id is available both for new and updated records by default if one chooses to use that as a unique identifiers either for directory or filename.

At this point I’ve written code to manually process uploaded files with File and mogrify. If we can get arc arc_ecto working seamlessly with the following, that would be ideal:

1. Upon creating a new record, it either lets you pass the existing logged in users id or any var. Currently that is not trivial.
2. File name versions match what’s stored in the db for original filename version. This does not work, there seems to be no connection between filename versions and what’s stored in the db as filename.
3. Upon delete, it deletes the original version filename and corresponding versions. That’s a valuable timesaver.

Without those 3 things, its only a little extra work to wire it yourself. There’s hidden magic in this plugin that makes ti difficult to get around the lifecycle.

Do we first create a record, get its id and then update it with the new version filename? But the lib does not store the file in cache, so that doesn’t seem workable.

Or do we change the filename versions and create the files first in the uploads folder and then store the updated name in the db?

**Comment by AppyCat** [comment]
I’ve emailed you a zip of my test project titled Arco.

You should get an email from We Transfer, which allows sending attachments no charge, it will have a link to download the zip.

If you have any time, I’d appreciate you checking my code, maybe I’m missing something that’s preventing arc or arc_ecto from reflecting the version filename in the db.

**Comment by AppyCat** [comment]
one@exelsites.com sent you some files

1 file, 40.1 MB in total
・ Will be deleted on 28 November, 2018


Download link:
https://wetransfer.com/downloads/e4490dbf00a0930550ff7072b9378df120181121025636/3846389b3b56c6d2571d5603b5e4272c20181121025636/d1a30f


Message:
Have attached Phoenix project ref arc and arc_ecto. Thanks for taking a look, maybe I
wired it wrong.



1 file

arco.zip


[Get more out of WeTransfer, get Plus](https://wetransfer.com/plus?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by AppyCat** [comment]
I have pretty much got everything working. Looking at your code was quite helpful, I wrote a function to sanitize empty spaces in a filename, and downcast, etc.

Small steps for mankind, a huge leap for me :) Good thing of burning hours on an issue is you learn it well long term. I’m still getting used to Elixir functional idiosyncrasies, but its like learning jazz for a musician, good for the health.

Thanks for all your help, if you could figure out why Arc is not storing the version filename, that would be great. I found deleting to be a bit of a pain with Arc, but accomplished it with File. Its likely my lack of understanding of the language that’s the problem.

Thanks again.

**Comment by AppyCat** [comment]
Btw, here’s my function. Please let me know if its fine or there’s a better approach in your experience:

defp trim_empty_spaces(changeset) do
    if get_field(changeset, :photo) != nil do
      f = get_field(changeset, :photo)
      new_name = String.replace(f.file_name, " ", "-")
      new_name = String.downcase(new_name)
      force_change(changeset, :photo, %{file_name: new_name, updated_at: DateTime.utc_now})
    else
      changeset
    end
  end
