### ISSUE TITLE
Storing a file without Plug.Upload

### ISSUE THREAD

**Issue by darksheik** [stavro/arc_ecto#11]
Your example passes a ```Plug.Upload``` parameter to store the file in the database.
Can you provide an example of an update that just uploads a file from your hard drive?

I want to be able to do something like this:
```
    model_record = Repo.get!(MyTable, 1)

    {:ok, filename} = MyProject.Attachment.store({path, model_record})
    Repo.update!(%{model_record | attachment: filename})
```

The file is successfully stored on S3, but I am not sure what the changeset is expecting me to pass.

**Comment by darksheik** [comment]
I figured out something that works, but not sure if it is correct.

```
Repo.update!(%{model_record | attachment: %{file_name: filename, updated_at: Ecto.DateTime.utc}})
```

**Comment by mrkaspa** [comment]
I need the same thing, I tried to fake the plug upload, but didn't work

```elixir
 params = %{
      avatar: %Plug.Upload{
        content_type: "image/jpeg",
        filename: "#{user.id}.jpeg",
        path: file_url
      }
    }
changeset = User.update_changeset(user, params)
response = Repo.update(changeset)

#THE CHANGESET METHOD
def update_changeset(model, params \\ :empty) do
    |> cast(params, @required_fields, @optional_fields)
    |> cast_attachments(params, @required_file_fields, @optional_file_fields)
end
```

**Comment by mrkaspa** [comment]
@darksheik so you had to upload the file manually and after that update the record on the database?

**Comment by stavro** [comment]
Hi Michel!  You don't need a Plug.Upload! Just create a regular Elixir map
with the filename and path and it should work just fine.

**Comment by mrkaspa** [comment]
@stavro I tried but doesn't work I'm testing with the lastest elixir version

**Comment by stavro** [comment]
Ok - I will be back in town on Tuesday and help resolve.  Apologies for the
confusion!

**Comment by darksheik** [comment]
Sorry I missed this activity!
Yes, uploading to S3 manually.  With my model set up to store the file on S3 in the "attachment" field (see the https://github.com/stavro/arc repo):

```
field :attachment, MyApp.Attachment.Type
```

I did this:
```
   {:ok, s3_filename} = MyApp.Attachment.store({local_filename, record})  # Upload to S3
   Repo.update!(%{record |
      attachment: %{file_name: s3_filename, updated_at: Ecto.DateTime.utc}}
    )
```

**Comment by mrkaspa** [comment]
@darksheik that worked for me but I don't think it be the best solution

**Comment by darksheik** [comment]
I agree - should just be able to do it in one go.

**Comment by stavro** [comment]
An example from the local harddrive:

```elixir
params = %{"avatar" => "/Users/sean/Downloads/picture.png"}

User
  |> Repo.get!(1)
  |> User.update_avatar(params)
  |> SchedWeb.Repo.update!

# models/user.ex

def update_avatar(user, params) do
  user
    |> cast_attachments(params, ~w(), ~w(avatar))
end
```
