### ISSUE TITLE
Fix Ecto 3.2 warnings

### ISSUE THREAD

**Issue by philipgiuliani** [stavro/arc_ecto#119]
I get the following warnings after updating to Ecto 3.2.

```
warning: function embed_as/1 required by behaviour Ecto.Type is not implemented (in module MyApp.Pdf.Type)

warning: function equal?/2 required by behaviour Ecto.Type is not implemented (in module MyApp.Pdf.Type)
```

**Comment by ndarilek** [comment]
Can I safely ignore these?

And any chance the fix will be merged?

Thanks!

**Comment by philipgiuliani** [comment]
@ndarilek Take a look at https://github.com/elixir-waffle/waffle and https://github.com/elixir-waffle/waffle_ecto

Its basically a fork of ARC, but with some improvements and its up to date with the current Elixir and Ecto version.

**Comment by bitboxer** [comment]
@stavro thanks for releasing the new version 💚
