### ISSUE TITLE
Uploads to S3 timeout 

### ISSUE THREAD

**Issue by Morganjackson** [stavro/arc_ecto#12]
I'm not sure if this is related to arc_ecto, ex_aws or httpoison so I'm sorry if this is the wrong place, but any file over roughly 300KB seem to time out with the error below:

``error] #PID<0.3140.0> running Agentport.Endpoint terminated``
``Server: localhost:4000 (http)``
``Request: POST /dashboard/posts``
``** (exit) exited in: Task.await(%Task{pid: #PID<0.3143.0>, ref: #Reference<0.0.6.9316>}, 10000)``
   `` ** (EXIT) time out``

Small images upload without any issues though.

**Comment by stavro** [comment]
Closed via https://github.com/stavro/arc/pull/26.

After upgrading `arc` to v0.2.2, you may bump this timeout through:

```elixir
config :arc,
  version_timeout: 30_000 #milliseconds
```

**Comment by stavro** [comment]
There's also a
```
 config :ex_aws, :httpoison_opts,
   recv_timeout: 30_000
```

which you might have to adjust if you expect to take longer than 30 seconds.
