### ISSUE TITLE
No file stored or storage_dir scope == nil

### ISSUE THREAD

**Issue by tompesman** [stavro/arc_ecto#13]
I've user model with an avatar field similar to the example here: https://github.com/stavro/arc_ecto#add-your-attachment-to-your-ecto-model

No file is stored when a file is uploaded. When I change the required/optional fields to this:

```elixir
  @required_fields ~w()
  @optional_fields ~w(name avatar) # <-- added avatar here

  @required_file_fields ~w()
  @optional_file_fields ~w(avatar)
```

A file is stored in `uploads`. When I change the `def storage_dir(version, {file, scope}) do` method to: `"uploads/users/avatar/#{scope.id}"` the scope field is empty. If I remove the avatar field from `@optional_fields` then the scope field is set, but no file is uploaded. I need both to work :wink:

Can you help me? Cheers!

**Comment by stavro** [comment]
Can I see your controller?

**Comment by tompesman** [comment]
It's a https://github.com/falood/maru api endpoint:

```elixir
defmodule Blog.UserApi do
  use Maru.Router

  params do
    optional :name, type: String
    optional :avatar, type: File
  end
  put "/user" do
    token = List.first(get_req_header(conn, "auth-token"))
    user = Blog.Repo.get_by(Blog.User, auth_token: token)

    IO.inspect params
    changeset = Blog.User.changeset_update(user, params)

    case Blog.Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_status(:ok)
        |> json(Blog.CurrentUserEntity.serialize(user))
      {:error, _changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> json(%{error: "Invalid request"})
    end
  end
end
```

The output of the `IO.inspect params` is:
```
%{avatar: %Plug.Upload{content_type: "image/png", filename: "1024.png",
   path: "/var/folders/85/gh23xrjx3pgdl8bd14lw6jx80000gn/T//plug-1450/multipart-790033-460458-8"},
  name: "Test"}
```

So the avatar field produces a `Plug.Upload`. That should be correct I think.

**Comment by tompesman** [comment]
Fixed it. Not sure if I'm sending something strange or the docs are missing a single char. :grimacing: 

```elixir
  @required_fields ~w()
  @optional_fields ~w(name)

  @required_file_fields ~w()
  @optional_file_fields ~w(avatar)a  # <-- added 'a' here
```

Or this line returns always an empty array: https://github.com/stavro/arc_ecto/blob/master/lib/arc_ecto/model.ex#L24

**Comment by stavro** [comment]
Interesting!  Your param keys are coerced to atoms, whereas a normal phoenix app they are not:

This is a typical params object (note the string keys, not atoms):
```
%{"avatar" => %Plug.Upload{content_type: "image/gif", filename: "nav.gif",
   path: "/var/folders/25/l2rtbqcs6k3bqpj3fldgnplw0000gn/T//plug-1450/multipart-980282-311833-6"},
  "business_id" => "1"}
```

**Comment by stavro** [comment]
It looks like Ecto under the hood converts them all to strings before processing.. We should do something similar here then.

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L413-L426

**Comment by stavro** [comment]
Closed via https://github.com/stavro/arc_ecto/commit/ceb5eb1cd21b2f2a22f75e4105977a12794e6619.

**Comment by tompesman** [comment]
Awesome! :smile: :+1:
