### ISSUE TITLE
cast_attachments not passing scope to storage_dir when trying to override

### ISSUE THREAD

**Issue by digitalcake** [stavro/arc_ecto#36]
I have an override for storage_dir in my uploader such as. 

```
def storage_dir(version, {file, scope}) do
    "uploads/posts/photo/#{scope.id}"
end
```

I'v observed that scope is nil and fails at `scope.id`

I'v also inspected cast_attachments's assignment of scope and have seen that is does assign scope correctly in the context of the macro

I have also observed that destination_dir = definition.storage_dir(version, {file, scope}) passes scope as nil

It looks as if cast_attachment's arc_params remain empty

**Comment by digitalcake** [comment]
I think I just found my problem. 

I was calling cast_attachments with the allowed as an atom. 
`cast_attachments(params, [:photo])`

when walking over the method I seen this. 


```pry(2)> Arc.Ecto.Schema.convert_params_to_binary(params)
%{"body" => "adsf", "draft" => "false", "excerpt" => "asdf",
  "photo" => %Plug.Upload{content_type: "image/jpeg", filename: "test.jpg",
   path: "/var/folders/tj/nrvjcskx27ngvqy58x545_2h0000gn/T//plug-1467/multipart-941212-44262-1"},
  "published_at" => %{"day" => "20", "hour" => "0", "minute" => "0",
    "month" => "1", "year" => "2011"}, "slug" => "20", "title" => "20"}
pry(3)> Arc.Ecto.Schema.convert_params_to_binary(params) |> Dict.take([:photo])
%{}     
pry(4)> Arc.Ecto.Schema.convert_params_to_binary(params) |> Dict.take(["photo"])
%{"photo" => %Plug.Upload{content_type: "image/jpeg", filename: "test.jpg",
   path: "/var/folders/tj/nrvjcskx27ngvqy58x545_2h0000gn/T//plug-1467/multipart-941212-44262-1"}}
```

**Comment by digitalcake** [comment]
Something else I'm seeing that is very odd to me is that in
arc_ecto/lib/arc_ecto/type.ex cast method where `definition.store(args)` is called both
`store(definition, {file, scope}) when is_binary(file) or is_map(file)` and `store(definition, filepath) when is_binary(filepath) or is_map(filepath)` are invoked.

**Comment by stavro** [comment]
What version of `arc_ecto` are you using? `Dict.take` should never have atoms, because it [converts atoms to strings](https://github.com/stavro/arc_ecto/blob/master/lib/arc_ecto/schema.ex#L19-L25).

**Comment by digitalcake** [comment]
@stavro you are correct, sorry I missed that. I was having issue debugging and tried to run the code by hand. That being said I can confirm both that cast methods are indeed being called at the same time.

**Comment by digitalcake** [comment]
Well this is embarrassing. It looks as if I was using arc 0.1 and arc_ecto 0.1
I'v updated both and still observe the same error

```
[error] Task #PID<0.415.0> started from #PID<0.410.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (digitalcakes) Digitalcakes.Imagable.storage_dir/2
    lib/arc/storage/s3.ex:5: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.62704849/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.410.0> (:cowboy_protocol) of listener Digitalcakes.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined or private
        nil.id()
        (digitalcakes) Digitalcakes.Imagable.storage_dir/2
        lib/arc/storage/s3.ex:5: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

**Comment by stavro** [comment]
Can you add the actual controller and changeset code? I don't have enough information to help you right now

**Comment by digitalcake** [comment]
@stavro https://gist.github.com/digitalcake/232a730f6bb1bd6ecae81dca1cc919b5

**Comment by stavro** [comment]
1. Remove `:photo` from your `cast` call.  It should not be present on `cast`, just `cast_attachments`.
2. You will not be able to use `scope.id` during model creation, because your model will not have an id yet.  You will either have to wait until the post is created, and then follow up with a subsequent call to `cast_attachments`, or you use some sort of uuid pattern.

**Comment by digitalcake** [comment]
Thank you for taking the time out and helping me.

**Comment by stavro** [comment]
Of course! If that doesn't work ping me in irc @stavro and I'll make sure you're situated. 👋

**Comment by digitalcake** [comment]
that was it, cast was also trying to invoke the uploader too which failed to set the scope correctly.

**Comment by iamwilhelm** [comment]
@stavro I have a question after reading the above thread. How do you make a subsequent call to `cast_attachments`? Can you provide an example? I'm trying to upload a file when the model is being created.

**Comment by ndarilek** [comment]
Hitting the exact same issue with Ecto 3.2, and I think something significant has changed. In particular, I *have* to include my attachment field in `cast`, otherwise none of the Arc functions seem to be hit.

I have a slightly odd situation in that I'm trying to import a document either from a URL or a file. Users can enter a URL into a text field or upload a file. For now I'm focusing on the URL use case. Here are some snippets from my model/controller:

```
defmodule Scribe.Documents.Document do
  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "documents" do
    field :name, :string
    field :original_url, EctoFields.URL
...
    field :original, ScribeWeb.Document.Type
...
  end

  def changeset(document, params \\ %{}) do
    IO.inspect(params)
    document
    |> cast(params, [:name, :original_url, :storage_upload_url, :input_format, :input_password, :is_input_password_needed, :input_page_count, :input_storage_key, :upload_file_name, :is_pdf_with_text, :input_processing_expected_page_count, :input_processing_completed_page_count])
    |> cast_attachments(params, [:original])
  end
end

defmodule ScribeWeb.DocumentController do
  use ScribeWeb, :controller
  plug :requires_auth, except: [:show]

...
  def create(conn, %{"document" => %{"original_url" => original_url} = document_params}) do
    user = conn.assigns[:current_user]
    case Documents.create_document(user, document_params) do
      {:ok, document} ->
        if document.original_url do
          {:ok, document} = Documents.update_document(document, %{"original" => original_url})
        end
        conn
        |> put_flash(:info, "Importing document...")
        |> redirect(to: Routes.document_path(conn, :show, document, "html"))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
...
end

defmodule ScribeWeb.Document do
  use Arc.Definition
  # Include ecto support:
  use Arc.Ecto.Definition

...
  # Override the storage directory:
  def storage_dir(_version, {_file, scope}) do
    IO.puts("Here")
    "#{scope.id}"
  end
...
end
```

With this code, the `IO.puts` in `storage_dir` never executes, even though the `IO.puts` in `changeset` shows that I'm calling it with `original`. If I add `:original` to the `cast` call, it does print, but then I experience the error in this issue, even though I defer setting `:original` until after the model is inserted.

Would really appreciate some help here, even if it's only to advise me to switch to something else. Given the warnings I get with Ecto 3.2, I'm worried that something has changed and that this library is now incompatible, but I've been out of Elixir/Phoenix for a few years and am not sure what current solutions exist for file storage.

Thanks.
