### ISSUE TITLE
Is it possible to persist full path of uploaded file?

### ISSUE THREAD

**Issue by atmlvs** [stavro/arc_ecto#69]
When to organize the upload folder structure, due to limitation count of subfolder, I have tried using UUID and date time, but it failed, seems filename() and storage_dir() are invoked in both store and get from database, so the expected resource url will be changed when query.

now I got an idea to use hash code of resource to organize the subfolder, but I am confused if this is the only way to do that, is there any other way such as persist full path in arc_ecto?

**Comment by pedep** [comment]
for more:
https://github.com/stavro/arc_ecto/issues/84
https://github.com/stavro/arc/issues/85
