### ISSUE TITLE
Todo: Support Ecto 3

### ISSUE THREAD

**Issue by mmartinson** [stavro/arc_ecto#98]
Ecto 3 is coming in the next couple days and with it the recommended upgrade path for those using it for database interaction is to change dependency from ecto to ecto_sql.

I think to support backwards compatibly for presumably a long time we'll want to introduce an optional dependency.

Reference [commit](https://github.com/elixir-ecto/ecto/commit/dc30e1b199dfd698cb28a21d8a1a2578705e5329) and [announcement](http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/)

**Comment by idyll** [comment]
One of the changes that's needed is in `cast_attachments`

The `allowed` params in:
```
cast(changeset_or_data, arc_params, allowed)
```
are converted into strings. Which triggers all sorts of warnings because they should be atoms.

**Comment by nathany** [comment]
It seems that the test suite doesn't require ecto_sql.

#101 amends #99 for Ecto 3.0 final. @tarzan resolved the warnings.

Do you want to support Ecto 2.x and 3.x simultaneously, or just release a new major version that requires Ecto 3? [people can always use an old version of arc_ecto]

**Comment by williamweckl** [comment]
Any updates on this?

**Comment by dbernheisel** [comment]
I think this issue is resolved with https://github.com/stavro/arc_ecto/pull/103

**Comment by williamweckl** [comment]
@dbernheisel Yes it is!
